export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const FETCH_SIMILAR_QUESTIONS = 'FETCH_SIMILAR_QUESTIONS';
export const SET_ACTIVE_QUESTION_NUMBER = 'SET_ACTIVE_QUESTION_NUMBER';
export const EXCHANGE_QUESTIONS = 'EXCHANGE_QUESTIONS';